apiVersion: batch/v1
kind: CronJob
metadata:
  name: mysql-backup-cleanup
  namespace: ams-backup
spec:
  schedule: "*/30 * * * *"  # Every 30 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cleanup
            image: busybox
            volumeMounts:
              - name: backup-storage
                mountPath: /backup
            command:
              - /bin/sh
              - -c
              - "find /backup/* -mmin +30 -exec rm {} \\;"  # Deletes files older than 30 minutes
          volumes:
          - name: backup-storage
            persistentVolumeClaim:
              claimName: mysql-backup-pvc
          restartPolicy: OnFailure