apiVersion: batch/v1
kind: CronJob
metadata:
  name: mysql-backup
  namespace: ams-backup
spec:
  schedule: "*/5 * * * *"  # Every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mysql-backup
            image: mysql:8.0
            env:
              - name: MYSQL_ROOT_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: db-secrets
                    key: root-password
              - name: MYSQL_USER
                valueFrom:
                  secretKeyRef:
                    name: db-secrets
                    key: user-username
              - name: MYSQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: db-secrets
                    key: user-password
              - name: MYSQL_HOST
                value: "mysql-service"  # Replace with the actual MySQL service name
              - name: MYSQL_NAMESPACE
                value: "mysql-namespace"  # Replace with the namespace where MySQL is running
            volumeMounts:
              - name: backup-storage
                mountPath: /backup
            command:
              - /bin/sh
              - -c
              - |
                mysqldump -h mysql-service.mysql-namespace.svc.cluster.local -u $MYSQL_USER -p$MYSQL_PASSWORD ams-app --single-transaction --quick --lock-tables=false > /backup/backup-$(date +\%F-\%T).sql
          volumes:
          - name: backup-storage
            persistentVolumeClaim:
              claimName: mysql-backup-pvc
          restartPolicy: OnFailure