apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-restore
  namespace: ams-backup
spec:
  template:
    spec:
      containers:
      - name: mysql-restore
        image: mysql:8.0
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: root-password
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: user-username
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: user-password
          - name: MYSQL_HOST
            value: "mysql-service"  # Replace with the actual MySQL service name
          - name: MYSQL_NAMESPACE
            value: "mysql-namespace"  # Replace with the namespace where MySQL is running
        volumeMounts:
          - name: backup-storage
            mountPath: /backup
        command:
          - /bin/sh
          - -c
          - |
            mysql -h mysql-service.mysql-namespace.svc.cluster.local -u $MYSQL_USER -p$MYSQL_PASSWORD ams-app < /backup/latest-backup.sql
      volumes:
      - name: backup-storage
        persistentVolumeClaim:
          claimName: mysql-backup-pvc
      restartPolicy: OnFailure