apiVersion: v1
kind: ConfigMap
metadata:
  name: db-cm
  namespace: ams-app
data:
  db-name: amsdbrest2024
  init.sql: |
    # -- Ensure you are using the correct database
    USE `amsdbrest2024`;

    # -- Create user if not exists (MySQL 8.0+ syntax)
    CREATE USER IF NOT EXISTS 'marwan'@'%' IDENTIFIED BY 'marwan123';

    # -- Revoke existing permissions (optional, if you want to reset all permissions)
    REVOKE ALL PRIVILEGES ON `amsdbrest2024`.* FROM 'marwan'@'%';

    # -- Grant updated permissions
    GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX ON `amsdbrest2024`.* TO 'marwan'@'%';

    # -- Apply changes
    FLUSH PRIVILEGES;

    # -- Create a simple table for employees
    CREATE TABLE IF NOT EXISTS `employees` (
        `id` INT AUTO_INCREMENT PRIMARY KEY,
        `first_name` VARCHAR(50) NOT NULL,
        `last_name` VARCHAR(50) NOT NULL,
        `email` VARCHAR(100) UNIQUE NOT NULL,
        `department` VARCHAR(50) NOT NULL,
        `salary` DECIMAL(10, 2) NOT NULL,
        `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    # -- Insert sample data into the employees table
    INSERT INTO `employees` (`first_name`, `last_name`, `email`, `department`, `salary`) VALUES
    ('John', 'Doe', 'john.doe@example.com', 'Engineering', 75000.00),
    ('Jane', 'Smith', 'jane.smith@example.com', 'Marketing', 68000.00),
    ('Mike', 'Johnson', 'mike.johnson@example.com', 'Sales', 60000.00),
    ('Emily', 'Davis', 'emily.davis@example.com', 'HR', 72000.00);

    # -- Create a simple table for departments
    CREATE TABLE IF NOT EXISTS `departments` (
        `id` INT AUTO_INCREMENT PRIMARY KEY,
        `name` VARCHAR(50) NOT NULL,
        `location` VARCHAR(100) NOT NULL
    );

    # -- Insert sample data into the departments table
    INSERT INTO `departments` (`name`, `location`) VALUES
    ('Engineering', 'New York'),
    ('Marketing', 'San Francisco'),
    ('Sales', 'Chicago'),
    ('HR', 'Boston');

    # -- Create a simple table for projects
    CREATE TABLE IF NOT EXISTS `projects` (
        `id` INT AUTO_INCREMENT PRIMARY KEY,
        `name` VARCHAR(100) NOT NULL,
        `description` TEXT,
        `start_date` DATE NOT NULL,
        `end_date` DATE,
        `department_id` INT,
        FOREIGN KEY (`department_id`) REFERENCES `departments`(`id`)
    );

    # -- Insert sample data into the projects table
    INSERT INTO `projects` (`name`, `description`, `start_date`, `end_date`, `department_id`) VALUES
    ('Project Alpha', 'A new initiative to improve customer experience.', '2024-01-15', '2024-12-31', 1),
    ('Project Beta', 'A marketing campaign for the new product launch.', '2024-03-01', NULL, 2);