apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pma
  name: pma
  namespace: ams-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pma
  template:
    metadata:
      labels:
        app: pma
    spec:
      containers:
      - image: phpmyadmin/phpmyadmin
        name: phpmyadmin
        ports:
        - containerPort: 80
        env:
        - name: PMA_HOST
          value:  mysql-service.ams-app.svc.cluster.local
        - name: PMA_PORT
          value: "3306" 
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: root-password
        - name: PMA_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: user-username
        - name: PMA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: user-password
---
apiVersion: v1
kind: Service
metadata:
  name: pma-service
  namespace: ams-app
spec:
  type: NodePort
  selector:
    app: pma
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80